services:
  db:
    image: mariadb:lts-ubi9
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "secret"
      MARIADB_DATABASE: "my_database"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  
  backup:
    image: mariadb:lts-ubi9 # Gebruik dezelfde image om mariadb-dump te garanderen
    profiles: ["backup"] # Maakt de service standaard niet actief
    volumes:
      # BELANGRIJK: Mount de lokale host map (met backups) in de container
      - ./backups:/backups
    # De command definieert de dump-logica, volledig in de container
    command: >
      bash -c "mariadb-dump
      --host=db
      --all-databases
      -u root
      -p$$MARIADB_ROOT_PASSWORD
      | gzip > /backups/db_dump_$(date +%Y%m%d_%H%M%S).sql.gz"
    environment:
      # Haal het wachtwoord op dezelfde manier op als de db service
      MARIADB_ROOT_PASSWORD: "secret"
    depends_on:
      - db

  app:
    build: .
    depends_on:
      - db
    tty: true
    volumes:
      - ./app:/home/appuser/app


  phpmyadmin:
    image: phpmyadmin:5.2.3-apache
    container_name: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - db

volumes:
  mariadb_data:
    driver: local